---
title: "OpenSnapsvisor v2.0.0"
subtitle: "github.com/ginger51011/snapsvisor.sh"
author: "Emil Eriksson (<emil@apkollen.se>) and Contributors"
geometry: margin=1in
header-includes:
  - \renewcommand*\familydefault{\ttdefault}
---
